name: Update check

on:
  workflow_dispatch:
  
  schedule:
    - cron: '*/20 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      if: runner.os != 'Windows'
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: '1.2.x' # default is 'stable'
    - uses: FedericoCarboni/setup-ffmpeg@v1
    - name: initialize git setting.
      run: |
        git config --global user.name "iranika"
        git config --global user.email "7370486+iranika@users.noreply.github.com"
        git remote set-url origin https://iranika:${GITHUB_TOKEN}@github.com/iranika/mo-code-4koma.git
        git pull
        git checkout master
    - name: check update momoirocode 
      run: |
        cd mosq
        nimble build -y
        cd ..
        ./mosq/bin/mosq update | grep -v "No updates" && \
        (git add 4koma/* 4komaData.json 4komaData.js 4komaData.js.org feed.atom update-info.dat && \
        git commit -m "update: auto updated 4komaData by workflow" && \
        git push origin master) || echo "No updates."
    - name: download top image
      run: |
        cd top
        pwsh ./download.ps1
        cd ..
        (git add top/top.jpg && git commit -m "top: image was changed" && (pwsh ./update-feed.ps1) && git add top/feed.atom && git commit -m "top: feed was updated." && git push origin master) || echo "No updates."
    - name: generate webp
      run: |
        pwsh generate-webp.ps1 && (git add 4koma/* top/top.* && git commit -m "update webp files." && git push origin master) || echo "No updates."
