name: download

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: FedericoCarboni/setup-ffmpeg@v2
    - name: initialize git setting.
      run: |
        git config --global user.name "iranika"
        git config --global user.email "7370486+iranika@users.noreply.github.com"
        git remote set-url origin https://iranika:${GITHUB_TOKEN}@github.com/iranika/mo-code-4koma.git
        git pull
        git checkout master
    - name: check update momoirocode 
      run: |
        ./mosq/download-img.ps1 && \
        pwsh generate-webp.ps1 && \
        (git add 4koma/* && \
        git commit -m "download: download image file" && \
        git push origin master) || echo "error download"
