name: Generate WebP Debug

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: FedericoCarboni/setup-ffmpeg@v1
    - name: initialize git setting.
      run: |
        git config --global user.name "iranika"
        git config --global user.email "7370486+iranika@users.noreply.github.com"
        git remote set-url origin https://iranika:${GITHUB_TOKEN}@github.com/iranika/mo-code-4koma.git
    - name: Setup PowerShell module cache
      id: cacher
      uses: actions/cache@v2
      with:
        path: "~/.local/share/powershell/Modules"
        key: ${{ runner.os }}-AngleParse
    - name: install module
      if: steps.cacher.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module AngleParse
    - name: generate-webp
      run: |
        pwsh ./mops/generate-4komaDataJs.ps1 -Debug
        pwsh ./mops/download-img.ps1 -OnlyRecently -Debug
        pwsh ./mops/generate-webp.ps1 -OnlyRecently -Debug
    - name: commit webp
      run: |
        (git add 4koma/* 4komaData.json 4komaData.js 4komaDataMin.js && git commit -m "debug: find update webp" && git push) || echo "No update."

